# .env and .pem file locations are hardcoded to be in the pwd (working dir)

version: "3.9"
services:
  ui:
    image: ghcr.io/the-codefun-exam-team/exam-frontend:latest
    networks: [ cfd-bridge ]
    restart: unless-stopped

  ui-ssr:
    image: ghcr.io/the-codefun-exam-team/frontend-ssr:latest
    networks: [ cfd-bridge ]
    env_file: data/ui-ssr.env
    restart: unless-stopped

  back:
    image: ghcr.io/the-codefun-exam-team/exam-backend:latest
    networks: [ cfd-bridge ]
    env_file: data/backend.env
    restart: unless-stopped

  proxy:
    image: ghcr.io/the-codefun-exam-team/proxy-server:latest
    networks: [ cfd-bridge ]
    ports:
    - 80:80
    - 443:443
    volumes:
    - type: bind
      source: data/cert.pem
      target: /cert/cert.pem
      read_only: true
    env_file: data/proxy.env
    restart: unless-stopped

networks:
  cfd-bridge:
    driver: bridge
