# .env and .pem file locations are hardcoded to be in the pwd (working dir)

version: "3.9"
services:
  db-pooler:
    image: edoburu/pgbouncer:1.22.0-p0
    restart: unless-stopped

    volumes:
    - type: bind
      source: /run/postgresql
      target: /run/postgresql
    - type: volume
      source: db-pooler-socket
      target: /run/pgbouncer

    env_file: data/db-pooler.env
    environment:
      - DB_HOST=/run/postgresql
      - LISTEN_ADDR=" "
      - AUTH_TYPE=trust
      - UNIX_SOCKET_DIR=/run/pgbouncer

  codefun-debug:
    depends_on: [ db-pooler ]
    image: ghcr.io/the-codefun-exam-team/codefun-debug:latest
    restart: unless-stopped

    networks: [ cfd-bridge ]
    volumes:
    - type: bind
      source: /run/postgresql
      target: /run/postgresql
    - type: volume
      source: db-pooler-socket
      target: /run/pgbouncer

    env_file: data/codefun-debug.env

  proxy:
    depends_on: [ codefun-debug ]
    image: haproxy:2.9.7-alpine
    restart: unless-stopped
    ports:
    - "${HTTP_BIND}:80"
    - "${HTTPS_BIND}:443"

    networks: [ cfd-bridge ]
    volumes:
    - type: bind
      source: data/cert.pem
      target: /cert/cert.pem
      read_only: true
    - type: bind
      source: data/haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
      read_only: true

    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    env_file: data/proxy.env

volumes:
  db-pooler-socket:

networks:
  cfd-bridge:
    driver: bridge
