# .env and .pem file locations are hardcoded to be in the pwd (working dir)

version: "3.9"
services:
  codefun-debug:
    image: ghcr.io/the-codefun-exam-team/codefun-debug:latest
    restart: on-failure:5

    networks: [ cfd-bridge ]
    volumes:
    - type: bind
      source: /run/postgresql
      target: /run/postgresql
    user: root
    env_file: data/codefun-debug.env

  proxy:
    depends_on: [ codefun-debug ]
    image: haproxy:2.9.7-alpine
    restart: on-failure:5
    ports:
    - "${HTTP_BIND}:80"
    - "${HTTPS_BIND}:443"

    networks: [ cfd-bridge ]
    volumes:
    - type: bind
      source: ./data/cert.pem
      target: /cert/cert.pem
      read_only: true
    - type: bind
      source: ./data/haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
      read_only: true

    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    env_file: data/proxy.env

networks:
  cfd-bridge:
    driver: bridge
