# .env and .pem file locations are hardcoded to be in the pwd (working dir)

version: "3.9"
services:
  ui:
    image: minhnhatnoe/codefun-debug-frontend:latest
    networks: [ cfd-bridge ]
    restart: unless-stopped

  ui-ssr:
    image: minhnhatnoe/codefun-debug-frontend-ssr:latest
    networks: [ cfd-bridge ]
    restart: unless-stopped

  back:
    image: minhnhatnoe/codefun-debug-backend:latest
    networks: [ cfd-bridge ]
    env_file: data/backend.env
    restart: unless-stopped

  proxy:
    image: minhnhatnoe/codefun-debug-proxy:latest
    networks: [ cfd-bridge ]
    ports:
    - 80:80
    - 443:443
    volumes:
    - type: bind
      source: data/cert.pem
      target: /cert/cert.pem
      read_only: true
    env_file: data/proxy.env
    restart: unless-stopped

networks:
  cfd-bridge:
    driver: bridge
